################ English language ##################
[en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1


################ Australia ##################
[au]
languageName = "Au"
languageCode = "en-au"
contentDir = "content/australia"
weight = 2

################ Bahrain ##################
[bh]
languageName = "Bh"
languageCode = "en-bh"
contentDir = "content/bahrain"
weight = 3

################ Canada ##################
[en-ca]
languageName = "Ca"
languageCode = "en-ca"
contentDir = "content/canada"
weight = 4

################ China ##################
[zh-hans]
languageName = "Zh"
languageCode = "zh-hans"
contentDir = "content/china"
weight = 5


################ Hong Kong ##################
[hk]
languageName = "Hk"
languageCode = "hk"
contentDir = "content/hongkong"
weight = 6

################ Japan ##################
[ja]
languageName = "Ja"
languageCode = "ja"
contentDir = "content/japan"
weight = 7